on:
  push:
    branches: [main]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - run: npm run chromatic
